export const sources = ['The Verge', 'CBS Sports', 'CNN', 'Kennedyspacecenter.com', 'Prideofdetroit.com', 'New York Post', 'The Wall Street Journal', 'Justinweather.com', 'The Times of India', 'MarketWatch', 'Gizmodo.com', 'Bloomberg', 'Associated Press', 'Fox News', 'Axios', 'WGHP FOX 8 Greensboro', 'Reuters', 'ABC News', 'The Guardian', 'New York Times'];
export const categories = ['general', 'Football', 'World news', 'US news', 'Technology', 'Politics', 'Opinion', 'U.S.', 'Real Estate', 'Theater', 'Food', 'World'];
export const authors = [
    'Sophie Tanno',
    'Jeremy Reisman',
    'Georgia Worrell',
    'The Wall Street Journal',
    'Justin Berk',
    'TOI World Desk',
    'William Watts',
    'Passant Rabie',
    'Jess Menton',
    'THE ASSOCIATED PRESS',
    'Chris Pandolfo',
    'April Rubin',
    'Emily Byrd, Dolan Reynolds, Justyn Araya DeBusk, Charles Ewing, Alex Schneider, Brayden Stamps',
    'Hyunjoo Jin, Jack Kim',
    'ABC News',
    'By Trip Gabriel',
    'By Andrew Duehren',
    'By Rukmini Callimachi and Mimi Dwyer',
    'By Josh Ocampo',
    'By Penelope Green',
    'By Sam Sifton',
    'By Nazaneen Ghaffar',
    'By Emma Bubola',
    'By Carol Rosenberg',
    'By Kenneth P. Vogel, Kim Barker, Constant Méheut and Michael Schwirtz',
    'NBC 10 NEWS',
    'Glenn Garner',
    'Tom Nicholson',
    'Lauren Izso, Hira Humayun, Nikki Carvajal',
    'Mike Florio',
    'JAKE COYLE',
    'https://www.facebook.com/peoplemag',
    'Vivien Lou Chen',
    'Al Weaver',
    'Avery Lotz',
    "Barron's",
    'Jacob Roach',
    'Joe Miller, Jennifer Hughes',
    'Associated Press',
    'Hannah Ziegler',
    'Sydney Barragan, Sierra van der Brug, Ryanne Mena',
    'Chris Raybon, Sean.koerner',
    'Josh Dinner',
    'The Hill',
    'Victor Mather',
    'Adam Clymer and Peter Baker',
    'Johnny Diaz',
    'Genevieve Ko',
    'Nazaneen Ghaffar',
    'Nicole Sperling',
    'Peter Baker',
    'Michael M. Grynbaum',
    'Alan Feuer and Charlie Savage',
    'Gina Kolata'
  ];